```{r}
library(devtools)
library(dplyr)
library(sf)
use_readme_rmd()
use_mit_license()
```

# Create data-raw folder to store raw datasets 

```{r}
usethis::use_data_raw()
```


# Package dependency

```{r}
usethis::use_package("sf")
```

```{r}
devtools::document()
```

# Generate datasets 

## High-Plains aquifer boundary

```{r}
hp_boundary <-
  sf::st_read("data-raw/hp_bound2010.shp") %>%
  dplyr::filter(AQUIFER == "High Plains aquifer") %>%
  dplyr::select(geometry) %>%
  st_transform(4269)

usethis::use_data(hp_boundary, overwrite = TRUE)
```

## Nebraska county boundaries

```{r}
ne_counties <-
  tigris::counties(state = "NE") %>%
  dplyr::select(STATEFP, COUNTYFP, NAME) %>%
  data.table::setnames(names(.), tolower(names(.)))

usethis::use_data(ne_counties, overwrite = TRUE)
```

## Railroads in Nebraska

(https://catalog.data.gov/dataset/tiger-line-shapefile-2019-nation-u-s-rails-national-shapefile)

```{r}
download.file("http://www2.census.gov/geo/tiger/TIGER2019/RAILS/tl_2019_us_rails.zip", destfile = "data-raw/us_rails.zip")

railroads_ne <-
  sf::st_read("data-raw/us_rails/tl_2019_us_rails.shp") %>%
  .[ne_counties, ] %>%
  dplyr::select(LINEARID)

usethis::use_data(railroads_ne, overwrite = TRUE)
```
