# Preparation

```{r}
library(devtools)
library(ggplot2)
library(data.table)
library(dplyr)
library(sf)

devtools::load_all()
```

# Generate datasets 

## Nebraska wells as sf

```{r}
data(wells_ne)

wells_ne_sf <-
  sf::st_as_sf(
    wells_ne,
    coords = c(
      "longdd",
      "latdd"
    ),
    crs = 4269
  ) %>%
  dplyr::mutate(gw_extracted = runif(nrow(.), min = 50, max = 200))

usethis::use_data(wells_ne_sf, overwrite = TRUE)
```

## High-Plains aquifer boundary

```{r}
hp_boundary <-
  sf::st_read("data-raw/hp_bound2010.shp") %>%
  dplyr::filter(AQUIFER == "High Plains aquifer") %>%
  dplyr::select(geometry) %>%
  st_transform(4269)

usethis::use_data(hp_boundary, overwrite = TRUE)
```

## Nebraska county boundaries

```{r}
ne_counties <-
  tigris::counties(state = "NE") %>%
  dplyr::select(STATEFP, COUNTYFP, NAME) %>%
  data.table::setnames(names(.), tolower(names(.)))

usethis::use_data(ne_counties, overwrite = TRUE)
```

## Railroads in Nebraska

(https://catalog.data.gov/dataset/tiger-line-shapefile-2019-nation-u-s-rails-national-shapefile)

```{r}
download.file("http://www2.census.gov/geo/tiger/TIGER2019/RAILS/tl_2019_us_rails.zip", destfile = "data-raw/us_rails.zip")

railroads_ne <-
  sf::st_read("data-raw/us_rails/tl_2019_us_rails.shp") %>%
  .[ne_counties, ] %>%
  dplyr::select(LINEARID)

usethis::use_data(railroads_ne, overwrite = TRUE)
```

## IA corn nitrogen

This is a made-up corn nitrogen use by county.

```{r}
set.seed(893434)

ia_nitrogen <-
  tigris::counties(state = "IA") %>%
  setnames(names(.), tolower(names(.))) %>%
  dplyr::select(countyfp) %>%
  dplyr::mutate(nitrogen_rate := runif(nrow(.), min = 100, max = 300))

usethis::use_data(ia_nitrogen, overwrite = TRUE)
```

## Hydrologic units

```{r}
ia_bbox <-
  st_bbox(ia_nitrogen) %>%
  st_as_sfc()

huc_ia <-
  st_read("data-raw/huc250k.shp") %>%
  st_transform(st_crs(ia_bbox)) %>%
  .[ia_bbox, op = st_within] %>%
  st_simplify(dTolerance = 100) %>%
  dplyr::select(HUC_CODE)

usethis::use_data(huc_ia, overwrite = TRUE)
```

## Yield and as-applied nitrogen

```{r}
soy_yield <-
  st_read("data-raw/yield-simple1.shp") %>%
  .[seq(1, nrow(.), by = 10), ] %>%
  dplyr::select("Yld_Vol_Dr") %>%
  rename(yield = Yld_Vol_Dr) %>%
  dplyr::mutate(yield_id = 1:nrow(.)) %>%
  st_transform_utm()

#--- remove non-ASCII character ---#
st_crs(soy_yield)$wkt <- gsub("°|º", "", st_crs(soy_yield)$wkt)

usethis::use_data(soy_yield, overwrite = TRUE)

as_applied_s_rate <-
  st_read("data-raw/as-applied-simple1.shp") %>%
  .[seq(1, nrow(.), by = 10), ] %>%
  dplyr::select("Rt_Apd_Ct_") %>%
  rename(seed_rate = Rt_Apd_Ct_) %>%
  dplyr::mutate(seed_id = 1:nrow(.)) %>%
  st_transform_utm()

#--- remove non-ASCII character ---#
st_crs(as_applied_s_rate)$wkt <- gsub("°|º", "", st_crs(as_applied_s_rate)$wkt)

usethis::use_data(as_applied_s_rate, overwrite = TRUE)

# ggplot() +
#   geom_sf(data = yield, size = 0.4, color = "red") +
#   geom_sf(data = as_applied_n_rate, size = 0.4, color = "blue")
```

# Basic sfg

## Points
```{r}
#--- create points ---#
point_1 <- st_point(c(2, 2))
point_2 <- st_point(c(1, 1))
point_3 <- st_point(c(1, 3))

#--- combine the points to make a single  sf of points ---#
points <- list(point_1, point_2, point_3) %>%
  st_sfc() %>%
  st_as_sf() %>%
  mutate(point_name = c("point 1", "point 2", "point 3"))

usethis::use_data(points, overwrite = TRUE)
```

## Lines

```{r}
#--- create lines ---#
line_1 <- st_linestring(rbind(c(0, 0), c(2.5, 0.5)))
line_2 <- st_linestring(rbind(c(1.5, 0.5), c(2.5, 2)))

#--- combine the points to make a single  sf of points ---#
lines <- list(line_1, line_2) %>%
  st_sfc() %>%
  st_as_sf() %>%
  mutate(line_name = c("line 1", "line 2"))

usethis::use_data(lines, overwrite = TRUE)
```

## Polygons

```{r}
#--- create polygons ---#
polygon_1 <- st_polygon(list(
  rbind(c(0, 0), c(2, 0), c(2, 2), c(0, 2), c(0, 0))
))

polygon_2 <- st_polygon(list(
  rbind(c(0.5, 1.5), c(0.5, 3.5), c(2.5, 3.5), c(2.5, 1.5), c(0.5, 1.5))
))

polygon_3 <- st_polygon(list(
  rbind(c(0.5, 2.5), c(0.5, 3.2), c(2.3, 3.2), c(2, 2), c(0.5, 2.5))
))

#--- combine the polygons to make an sf of polygons ---#
polygons <- list(polygon_1, polygon_2, polygon_3) %>%
  st_sfc() %>%
  st_as_sf() %>%
  mutate(polygon_name = c("polygon 1", "polygon 2", "polygon 3"))

usethis::use_data(polygons, overwrite = TRUE)
```
